version: '3'

services:
  minimal-redamber:
    build:
      context: .
      dockerfile: Dockerfile
    image: red_amber-minimal-notebook
    container_name: red_amber-minimal-notebook
    user: root
    environment:
      - GRANT_SUDO=yes
      - NB_USER=$NB_USER
      - CHOWN_HOME=yes
      - TZ=$TZ
    working_dir: /home/$NB_USER/work
    ports:
      - '8888:8888'
    volumes:
      - ../doc/notebook:/home/$NB_USER/work
    command: start-notebook.sh --NotebookApp.token=$TOKEN
