# frozen_string_literal: true

source 'https://rubygems.org'

gem 'irb'

gem 'numo-narray'
gem 'red-arrow', '~> 12.0.0'
gem 'red-arrow-numo-narray'
gem 'red-parquet', '~> 12.0.0'

gem 'red_amber'
gem 'red-amber-view'
gem 'rover-df'

gem 'red-datasets'
gem 'red-datasets-arrow'

gem 'benchmark_driver'
gem 'benchmark-ips'

gem 'charty'
gem 'faker'
gem 'matplotlib'
gem 'pycall'
gem 'unicode_plot'
