# frozen_string_literal: true

source 'https://rubygems.org'

gem 'irb'

gem 'numo-narray'
gem 'red-arrow', '~> 11.0.0'
gem 'red-arrow-numo-narray'
gem 'red-parquet', '~> 11.0.0'

gem 'red_amber', '>=0.4.0'
gem 'red-amber-view'
gem 'rover-df'

gem 'red-datasets'
gem 'red-datasets-arrow'

gem 'benchmark_driver'
gem 'benchmark-ips'
gem 'faker'
