name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu, macos] # windows, if: runner.os == 'Windows'
        ruby: ['3.0', '3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Apache Arrow on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          rm -f /usr/local/bin/2to3* || :
          rm -f /usr/local/bin/idle3* || :
          rm -f /usr/local/bin/pydoc3* || :
          rm -f /usr/local/bin/python3* || :
          rm -f /usr/local/bin/python3-config || :

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          bundle install

      - name: Run test
        run: bundle exec rake test

      # - name: Check test coverage
      #   if: runner.os == 'Linux' && matrix.ruby == '3.1'
      #   uses: joshmfrankel/simplecov-check-action@main
      #   with:
      #     minimum_suite_coverage: 98
      #     minimum_file_coverage: 90
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
