name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu, macos] # windows, if: runner.os == 'Windows'
        ruby: ['3.0', '3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Apache Arrow on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y -V ca-certificates lsb-release wget
          wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
          sudo apt install -y -V libarrow-dev libarrow-glib-dev gobject-introspection

      - name: Prepare Apache Arrow on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          rm -f /usr/local/bin/2to3* || :
          rm -f /usr/local/bin/idle3* || :
          rm -f /usr/local/bin/pydoc3* || :
          rm -f /usr/local/bin/python3* || :
          rm -f /usr/local/bin/python3-config || :
          brew update
          brew install apache-arrow
          brew install gobject-introspection
          brew install apache-arrow-glib

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # ignore contents of the cache and get and build all the gems anew

      - name: Run test
        run: bundle exec rake test

      # - name: Check test coverage
      #   if: runner.os == 'Linux' && matrix.ruby == '3.1'
      #   uses: joshmfrankel/simplecov-check-action@main
      #   with:
      #     minimum_suite_coverage: 98
      #     minimum_file_coverage: 90
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
